class_name BattleData

const FATHER_STATS := {
	"name": "Father",
	"max_hp": 60,
	"max_mp": 20,
	"atk": 15,
	"def": 10,
	"spd": 8,
	"level": 4,
	"spells": ["hurt"],
}

const SON_STATS := {
	"name": "Son",
	"max_hp": 50,
	"max_mp": 25,
	"atk": 12,
	"def": 8,
	"spd": 10,
	# Son starts at Lv 7: DQ1 level gates filter his known_spells list
	# so he has Heal (L3), Hurt (L4), Sleep (L7) available at battle
	# start, but Stopspell (L10) and Healmore (L15) stay gated until a
	# level-up system is wired. The full kit is listed so a future
	# set_level(N) path reveals them as Son levels up, no schema churn.
	"level": 7,
	"spells": ["heal", "healmore", "hurt", "sleep", "stopspell"],
}

const ALLY1_STATS := {
	"name": "Ally1",
	"max_hp": 45,
	"max_mp": 30,
	"atk": 10,
	"def": 7,
	"spd": 9,
	"level": 2,
	"spells": [],
}

const ALLY2_STATS := {
	"name": "Ally2",
	"max_hp": 65,
	"max_mp": 10,
	"atk": 14,
	"def": 12,
	"spd": 6,
	"level": 2,
	"spells": [],
}

# Fallback stats above are kept for tests and early dev. In production,
# main.gd uses build_hero_from_curve() to construct party members from
# LevelCurve .tres files generated by the vault → articy → adapter pipeline.

static func build_hero_from_curve(hero_name: String, level: int, stat_curve: LevelCurve, spells: Array[String] = []) -> Dictionary:
	"""Build a party member dict from a stat growth curve at the given level."""
	return {
		"name": hero_name,
		"max_hp": stat_curve.stat_at_level("max_hp", level),
		"max_mp": stat_curve.stat_at_level("max_mp", level),
		"atk": stat_curve.stat_at_level("atk", level),
		"def": stat_curve.stat_at_level("def", level),
		"spd": stat_curve.stat_at_level("spd", level),
		"level": level,
		"spells": spells,
	}

static func calc_damage(atk: int, def: int) -> int:
	var base = atk - def / 2
	var variance = randi_range(-2, 2)
	return maxi(1, base + variance)

static func calc_flee_chance(party_spd: int, enemy_spd: int) -> bool:
	var chance = 0.5 + 0.1 * (party_spd - enemy_spd)
	chance = clampf(chance, 0.1, 0.9)
	return randf() < chance
